version: '3'
services:
  base_modelapi:
    image: dzigen/base_model_api:v1
    build: ./base_model_api

  modelapi:
    image: dzigen/model_api:v1
    build: ./modelapi
    container_name: modelapi_cntname
    hostname: model_api
    ports:
      - 4567:4567
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes: 
      - ${PWD}/modelapi/logs:/home/logs
      - type: bind
        source: ${PWD}/modelapi/.env
        target: /home/app/.env
    depends_on:
      - mongoui

  # Jenkins server
  jenkins:
    image: jenkins_with_dockercli:v1
    build: ./jenkins_with_dockercli
    container_name: jenkins_cntname
    hostname: jenkins
    ports:
      - 8080:8080
      - 8090:8090
      - 50000:50000
    user: root
    group_add:
      - 0
    volumes:
      - /home/dzigen/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/dzigen/.cache/pydrive2fs/:/root/.cache/pydrive2fs/
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  # Environment for functional testing
  test_modelapi:
    image: dzigen/test_model_api:v1
    build: ./test_model_api
    container_name: test_modelapi_cntname
    hostname: test_model_api
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      - modelapi

  # Database - Mongo DB
  mongodb:
    image: dzigen/mongodb:v1
    build: ./mongodb
    container_name: mongodb_cntname
    hostname: mongo
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /home/dzigen/mongo_volume:/data/db

  # Database manager
  mongoui:
    image: mongo-express:1.0.2
    ports:
      - 8099:8081
    container_name: mongoui_cntname
    hostname: mongo_express
    env_file:
      - .env
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD
      - ME_CONFIG_MONGODB_PORT
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_SERVER
    depends_on:
      - mongodb