stages:
  prepare:
    cmd: python src/preprocess.py
    deps:
    - src/preprocess.py
    - data/BankNote_Authentication.csv
    params:
    - prepare.train_size
    - prepare.seed
    outs:
    - experiments/train_part.csv
    - experiments/test_part.csv
  
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - experiments/train_part.csv
    params:
    - train.n_estimators
    - train.criterion
    - train.max_depth
    - train.min_samples_split
    - train.min_samples_leaf
    - train.min_weight_fraction_leaf
    - train.max_features
    - train.max_leaf_nodes
    - train.min_impurity_decrease
    - train.bootstrap
    - train.oob_score
    - train.random_state
    - train.warm_start
    - train.class_weight
    - train.ccp_alpha
    - train.max_samples
    - train.monotonic_cst
    outs:
    - experiments/model.pkl

  evaluate:
    cmd: python src/predict.py
    deps: 
    - experiments/model.pkl
    - src/predict.py
    - experiments/test_part.csv
    metrics:
    - experiments/metrics.json:
        cache: false