prepare:
  train_size: 0.8
  seed: 2

train:
    n_estimators: 400
    criterion: 'gini'
    max_depth: null
    min_samples_split:  2
    min_samples_leaf: 1
    min_weight_fraction_leaf:  0.0
    max_features: 'sqrt'
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: True
    oob_score: False
    random_state: null
    warm_start: False
    class_weight: null
    ccp_alpha: 0.0
    max_samples: null
    monotonic_cst: null
    n_jobs: 2
    verbose: 1

